import type { Service, Hours } from "./types";
export const config = {
  name: "Barbearia do Enzo",
  slogan: "Seu estilo, nossa paixão.",
  description:
    "Mais que um corte, uma experiência. Estilo, atitude e qualidade em cada detalhe.",
  address: "Rua das Estrelas, 123",
  city: "São Paulo – SP",
  whatsapp: "5562999577706",
  instagram: "barbeariadoenzo",
  timezone: "America/Bahia",
  pin: "1234",
  step: 30,
  leadMinutes: 60,
  windowDays: 30,
  colors: {
    background: "#0e0e10",
    surface: "#18181b",
    accent: "#c9a45c",
    text: "#f5f1e8",
  },
  barbers: [{ id: "rafael", name: "Rafael Lima", image: "images/barber.svg" }],
  lunch: { enabled: true, start: 690, end: 810, weekdays: [1, 2, 3, 4, 5] },
};
export const initialHours: Hours[] = Array.from({ length: 7 }, (_, day) => ({
  open: 540,
  close: 1200,
  closed: day === 0,
}));
export const initialServices: Service[] = [
  {
    id: "corte",
    name: "Corte de Cabelo",
    description: "Seu corte, sua identidade. Acabamento preciso e finalização.",
    price: 50,
    duration: 30,
    active: true,
    icon: "scissors",
  },
  {
    id: "barba",
    name: "Barba",
    description: "Desenho alinhado, toalha quente e cuidado em cada detalhe.",
    price: 40,
    duration: 30,
    active: true,
    icon: "razor",
  },
  {
    id: "combo",
    name: "Corte + Barba",
    description: "O ritual completo. Um novo visual, do cabelo à barba.",
    price: 80,
    duration: 60,
    active: true,
    featured: true,
    icon: "combo",
  },
  {
    id: "sobrancelha",
    name: "Sobrancelha",
    description: "Um ajuste sutil que faz toda a diferença.",
    price: 20,
    duration: 15,
    active: true,
    icon: "brow",
  },
  {
    id: "completo",
    name: "Corte + Barba + Sobrancelha",
    description: "Tempo reservado para cuidar de você por inteiro.",
    price: 100,
    duration: 75,
    active: true,
    icon: "combo",
  },
  {
    id: "infantil",
    name: "Corte infantil",
    description: "Paciência, conforto e um corte cheio de personalidade.",
    price: 35,
    duration: 30,
    active: true,
    icon: "scissors",
  },
];
